### ISSUE TITLE
The search bar breaks on firefox

### ISSUE THREAD

**Issue by andresgrdn** [andresgrdn/clon-google#1]
In chrome it doesn't need margin-inline auto but in firefox it breaks, and align itself to the left.

**Comment by NisooJadhav** [comment]
I tried various methods I knew but nothing worked, just wrap it in the center tag
![Untitled](https://user-images.githubusercontent.com/68807845/174822812-0274071e-4470-4a9b-a66e-8256285f7659.png)

**Comment by andresgrdn** [comment]
Thanks @NisooJadhav, the center tag is no longer in the standard so I'd rather not use it. But thanks for helping me here.
